php: Autospec creation for update from version 8.1.4 to version 8.1.5
Bob Weinand (3):
      Fix GH-8176: Fix leaking enum values in property initializers
      Fix freeing of internal attribute arguments
      Fix ZTS build after cherry-pick

Christoph M. Becker (7):
      Fix GH-8121: SplFileObject - seek and key with csv file inconsistent
      Fix GH-8068: mysqli_fetch_object creates inaccessible properties
      Fix typo (--EXTENSION-- → --EXTENSIONS--)
      Fix GH-8208: mb_encode_mimeheader: $indent functionality broken
      Fix signedness confusion in php_filter_validate_domain()
      Fix result_type related stack corruption on LLP64 architectures
      Fix GH-8253: pg_insert() fails for references

David Carlier (2):
      Fix GH-8142: Compilation error on cygwin
      Fix Solaris builds of ext/sockets

Dmitry Stogov (13):
      Fix non-reentirant startiong or error recording from error handler
      Fixed memory leak
      Tracing JIT: Eliminate useless guards for CONCAT
      Optimizer: Fix inorrect constant substitution in FETCH_LIST_R
      JIT: Fix type store
      JIT: Fix register allocation
      Fix memory leak
      Skip test for preloading
      JIT: Fix missing exception handling
      JIT: Fix memory leak
      JIT: Fix missing type store
      JIT: Fix register clobbering
      JIT: Fixed memory leak

Ilija Tovilo (3):
      Allowing catching arg type deprecations in intl classes
      Fix IntlPartsIterator key off-by-one error
      Register JSON_ERROR_NON_BACKED_ENUM constant (#8285)

Kamil Tekiela (2):
      Fix regression from #8058
      Fix mnd_malloc -> mnd_emalloc from previous merge

Michael Voříšek (1):
      Fix GH-8160: ZTS support on Alpine is broken

Nikita Popov (1):
      Make DirectoryIterator current() / key() return types tentative

Patrick Allaert (3):
      Bump for 8.1.5-dev
      Update NEWS for PHP 8.1.5RC1
      Update versions for PHP 8.1.5RC1

Remi Collet (2):
      run-tests.php: fix TypeError: Unsupported operand types: string * int <n> is mandatory for --show-slow and --set-timeout use <n> in help message instead of confusing [n]
      typo

Stanislav Malyshev (1):
      Don't try to access memory outside string

Tim Düsterhus (2):
      Fix memory leak of function attribute hash table (#8070)
      Add tests for function parameter attributes to ext/zend_test

risner (1):
      Fix GH-8048: disk_*_space wrong for some filesystems on macOS