php: Autospec creation for update from version 7.3.3 to version 7.3.4
Abyr Valg (1):
      OpenSSL: Improve non-blocking eof test

Anatol Belski (6):
      Sync with behavior change in OpenSSL 1.1.1b
      Fix test portability
      Sync with behavior change in OpenSSL 1.1.1b
      Fixed bug #77576 pull the libmagic implementation of gmtime_r
      Update libmagic.patch [skip ci]
      Die hard if mc.exe or mt.exe not found

Christoph M. Becker (12):
      Prepare main branch for PHP 7.3.4
      Fix #77648: BOM in sapi/apache2handler/php_functions.c
      Fix #77431 SplFileInfo::__construct() accepts NUL bytes
      Update NEWS
      Update NEWS
      Fix #77700: Writing truecolor images as GIF ignores interlace flag
      Fix #76956: Wrong value for 'syslog.filter' documented in php.ini
      Add bison version check to configure
      Fix #77578: Crash when php unload
      Fix order
      Update version for PHP 7.3.4RC1
      Revert "Fix #77609: Tests from mailparse extension fails"

Christopher Jones (1):
      Correct skipif use for OCI8 password tests

Derick Rethans (2):
      Fixed bug #50020 (DateInterval:createDateFromString() silently fails)
      Fixed 7.2 compat issue

Dmitry Stogov (2):
      Fixed bug #77345 (Stack Overflow caused by circular reference in garbage collection)
      ws

Fabien Villepinte (1):
      Fix typo in libmagic version

Frank Denis (2):
      Fix bug #77646
      Fix bug #77646

Ignace Nyamagana Butera (1):
      Fixed bug #75113: Added DatePeriod::getRecurrences() method.

Jakub Zelenka (4):
      Use spaces instead of tabs in bug 77390 test
      Print empty string in test for but 77390 just once
      Speed up TLS wrapper tests when SSLv3 disabled
      Speed up TLS wrapper test for min and max versions

Jay Satiro (1):
      curl_error: return an empty string if no error occurred

Joe Watkins (2):
      bump versions after release
      fix news

Kevin Adler (2):
      Fix bug #77677: WCOREDUMP not available on all systems
      Fix shared module generation on AIX bug #77676

Miriam Lauter (1):
      Fix #77767: phpdbg break command help message shows incorrect aliases

Nikita Popov (19):
      Fix issue mentioned in #77302
      Fixed bug #77597
      Fixed bug #77652
      Fix inference warning about missing key type
      Remove result def during jmp_set optimization
      Fix assertion in Exception::getMessage() if $message is a ref
      Fixed bug #77669
      Check for NULL GC type in objects_store_del
      Fixed bug #77691
      Fixed bug #76717
      Fixed bug #77722
      Fixed bug #77742
      Don't immediately destroy curl pushfunction
      Fix unused variable warning
      Remove x86 bit test optimization
      Fixed bug #77743
      Partial fix for bug #77751
      Allow DateTimeImmutable in datefmt_format_object()
      Make test independent of icu version

Pedro Magalhães (1):
      Added test for #77535 fix

Peter Kokot (3):
      Update NEWS
      Update NEWS
      Update editorconfig

Ralf Habacker (1):
      Fix #77609: Tests from mailparse extension fails

Remi Collet (3):
      bump version to 7.2.17-dev
      add NEWS entries
      add NEWS entry

Stanislav Malyshev (8):
      Fix bug #77396 - Null Pointer Dereference in phar_create_or_parse_filename
      Fix integer overflows on 32-bits
      Fix bug #77540 - Invalid Read on exif_process_SOFn
      Fix bug #77563 - Uninitialized read in exif_process_IFD_in_MAKERNOTE
      Fix test error message
      Update NEWS
      Fix bug #77586 - phar_tar_writeheaders_int() buffer overflow
      Fix bug #77630 - safer rename() procedure

Vlad Temian (1):
      Fixed bug #77765

Xinchen Hui (9):
      Fixed bug #77664 (Segmentation fault when using undefined constant in custom wrapper)
      Update NEWS
      Fixed bug #77660 (Segmentation fault on break 2147483648)
      Update NEWS
      Fixed compiler warning
      Fixed bug #77738 (Nullptr deref in zend_compile_expr)
      updated NEWS
      Fixed bug #77697 (Crash on Big_Endian platform)
      Simplfy test case

bohwaz (1):
      SQLite3: add DEFENSIVE config for SQLite >= 3.26.0 as a mitigation strategy against potential security flaws

twosee (1):
      Don't disable object slot reuse while running shutdown functions